apiVersion: kuma.io/v1alpha1
kind: MeshAccessLog
metadata:
  name: maltcp
  namespace: kuma-system
  labels:
    kuma.io/mesh: default # optional, defaults to `default` if it isn't configured
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/protocol: 'tcp'
  from:
  - targetRef:
      kind: Mesh
    default:
      backends:
      - type: File
        file:
          path: /dev/stdout
          format:
            type: Plain
            plain: "[%START_TIME%] %KUMA_MESH% %KUMA_SOURCE_ADDRESS_WITHOUT_PORT%(%KUMA_SOURCE_SERVICE%)->%UPSTREAM_HOST%(%KUMA_DESTINATION_SERVICE%) took %DURATION%ms, sent %BYTES_SENT% bytes, received %BYTES_RECEIVED% bytes"
  to:
  - targetRef:
      kind: Mesh
    default:
      backends:
      - type: File
        file:
          path: /dev/stdout
          format:
            type: Plain
            plain: "[%START_TIME%] %KUMA_MESH% %KUMA_SOURCE_ADDRESS_WITHOUT_PORT%(%KUMA_SOURCE_SERVICE%)->%UPSTREAM_HOST%(%KUMA_DESTINATION_SERVICE%) took %DURATION%ms, sent %BYTES_SENT% bytes, received %BYTES_RECEIVED% bytes"