apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slack-github-agent-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tomtomtomtom44/slack-github-ai-agent.git'
    targetRevision: HEAD
    path: helm/slack-github-agent
    helm:
      valueFiles:
        - values.yaml
        - values.staging.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: slack-github-agent-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
