# Nom de l'environnement
environment: prod

# Espace de noms de destination pour la production
destinationNamespace: slack-github-agent

# Espace de noms de l'application linguaplay
linguaplayNamespace: linguaplay