apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets-kuma
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-kuma

  target:
    name: kuma-tls-cert
    template:
      type: kubernetes.io/tls
      metadata:
        labels:
          app.kubernetes.io/managed-by: Helm
        annotations:
          meta.helm.sh/release-name: my-kuma-release
          meta.helm.sh/release-namespace: kuma-system

  # dataFrom will fetch all secrets that are inside the 'secretsPath'. When 'recursive' is
  # enabled, it will also fetch all secrets recursively in sub-directories.
  dataFrom:
    - find:
        name:
          regexp: .*
